proxy:
  # Nonexistent server
  - ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprSzdEdHQ0MkJLOE9hRjBKYjdpWGFK@1.1.1.1:9953/?outline=1
  # Revoked key
  - ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprSzdEdHQ0MkJLOE9hRjBKYjdpWGFK@159.203.76.146:9953/?outline=1
  # Good key
  - ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpxYXJNZEJ0VkYyamhaMnFFWGRtNWFY@159.203.76.146:9953/?outline=1