dns:
  # We get censored DNS responses when we send queries to an IP in China.
  - udp: { address: china.cn }
  # We get censored DNS responses when we send queries to a resolver in Iran.
  - udp: { address: ns1.tic.ir }
  - tcp: { address: ns1.tic.ir }
  # We get censored DNS responses when we send queries to an IP in Turkmenistan.
  - udp: { address: tmcell.tm }
  # We get censored DNS responses when we send queries to a resolver in Russia.
  - udp: { address: dns1.transtelecom.net. }
  # Testing captive portal.
  - tls:
      name: captive-portal.badssl.com
      address: captive-portal.badssl.com:443
  # Testing forged TLS certificate.
  - https: { name: mitm-software.badssl.com }

tls:
  - ""
  - split:1
  - split:2
  - split:5
  - tlsfrag:1

fallback:
  # Nonexistent Outline Server
  - configUrl: ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprSzdEdHQ0MkJLOE9hRjBKYjdpWGFK@1.2.3.4:9999/?outline=1
  # Nonexistant Psiphon Config. Not yet supported
  - psiphon: {
      LocalHttpProxyPort: 8081,
      LocalSocksProxyPort: 1081,
      PropagationChannelId: FFFFFFFFFFFFFFFF,
      RemoteServerListDownloadFilename: remote_server_list,
      RemoteServerListSignaturePublicKey: MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiVpJfzq/xvL9SBH5rIFnk0RXYEYavax3WS6HOD35eTAqn8AniOwiH +DOkvgSKF2caqk/y1dfq47Pdymtwzp9ikpB1C5OfAysXzBiwVJlCdajBKvBZDerV1cMvRzCKvKwRmvDmHgphQQ7WfXIGbRbmmk6opMBh3roE42KcotLFtqp0RRwLtcBRNtCdsrVsjiI1Lqz/lH+T61sGjSjQ3CHMuZYSQJZo/KrvzgQXpkaCTdbObxHqb6/+i1qaVOfEsvjoiyzTxJADvSytVtcTjijhPEV6XskJVHE1Zgl+7rATr/pDQkw6DPCNBS1+Y6fy7GstZALQXwEDN/qhQI9kWkHijT8ns+i1vGg00Mk/6J75arLhqcodWsdeG/M/moWgqQAnlZAGVtJI1OgeF5fsPpXu4kctOfuZlGjVZXQNW34aOzm8r8S0eVZitPlbhcPiR4gT/aSMz/wd8lZlzZYsje/Jr8u/YtlwjjreZrGRmG8KMOzukV3lLmMppXFMvl4bxv6YFEmIuTsOhbLTwFgh7KYNjodLj/LsqRVfwz31PgWQFTEPICV7GCvgVlPRxnofqKSjgTWI4mxDhBpVcATvaoBl1L/6WLbFvBsoAUBItWwctO2xalKxF5szhGm8lccoc5MZr8kfE0uxMgsxz4er68iCID+rsCAQM=,
      RemoteServerListUrl: https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed,
      SponsorId: FFFFFFFFFFFFFFFF,
      UseIndistinguishableTLS: true
    }
  # Nonexistant local socks5 proxy
  - configUrl: socks5://192.168.1.10:1080

