// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function TestConnectivity(arg1:string,arg2:string,arg3:Array<string>,arg4:main.ConnectivityTestProtocolConfig):Promise<Array<main.ConnectivityTestResult>>;
