#This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
#goland is very language best for build any app like this 
#you can build this ans commit change any interface for customize any app
#social-histfx will help you to get any best way to get app for get this file
#social-hostfx is snobuyhostfx you need to understqnd well about this system for any question ask snobuyhostfx
#welcome to hostfx dev ask confence or email

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
