name: Release Mobileproxy

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The existing release tag to upload assets to (e.g., x/v0.0.3). The release for this tag must already exist.'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release_mobileproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/x/go.mod"

      - name: Install GitHub CLI
        uses: cli/setup-gh@v2

      # Using a separate bash script for easier testing
      - name: Release Mobileproxy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/release-mobileproxy.sh ${{ inputs.release_tag }}
